import { vi } from 'vitest'

process.env['NODE_ENV'] = 'test'
process.env['DATABASE_URL'] = 'postgresql://test:test@localhost:5432/test'
process.env['REDIS_HOST'] = 'localhost'
process.env['REDIS_PORT'] = '6379'
process.env['REDIS_PASSWORD'] = 'testpassword'
process.env['JWT_ACCESS_SECRET'] = 'test-access-secret-minimum-32-chars-long'
process.env['ENCRYPTION_KEY'] = 'dGVzdGtleXRlc3RrZXl0ZXN0a2V5dGVzdGtleXRlc3Q='
process.env['LOG_LEVEL'] = 'silent'
